### PR TITLE
Updates so it can be played right out of the box.

### PR DESCRIPTION
**Pull request by welcome-me**
Played until I lost. I wonder what other functionality could be added if the js file was 1000 bytes ... ? :smile:

### CODE REVIEW

**Comment by XtremePlayzCODE** [comment]
Hmm. Maybe we can do 1000 bytes. You could try it if you want and add it to this pull

**Comment by welcome-me** [comment]
Maybe I'll try it sometime... :D

~ Jefré

**Comment by XtremePlayzCODE** [comment]
Cool! Gonna make a new project

**Comment by XtremePlayzCODE** [comment]
Basically it's a clone of Node and V8

**Pull request merged**
